import { createGetInitialProps } from '@mantine/next';
import Document, { Head, Html, Main, NextScript } from 'next/document';
import { JSX } from 'react';

const getInitialProps = createGetInitialProps();

export default class _Document extends Document {

  static getInitialProps = getInitialProps;

  render(): JSX.Element {
    return (
      <Html lang="en">

        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link href="https://fonts.googleapis.com/css2?family=Acme&family=Hind&display=swap" rel="stylesheet" />
        </Head>

        <body>
          <Main />
          <NextScript />
        </body>

      </Html>
    )
  }

}
