import { createGetInitialProps } from '@mantine/next';
import Document, { Head, Html, Main, NextScript } from 'next/document';
import { JSX } from 'react';

const getInitialProps = createGetInitialProps();

export default class _Document extends Document {

  static getInitialProps = getInitialProps;

  render(): JSX.Element {
    return (
      <Html lang="en">
  
        <Head>
          <title>Fridgefy | Search Today's Recipe</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <body>
          <Main />
          <NextScript />
        </body>
  
      </Html>
    )
  }

}
